adding PyTest and github workflow.
redhat-beyond/MeetBalls pull request #29
Opened 2023-04-16 13:48 UTC by IdanZimi

added PyTest to pipfile.
added pytest.yml file which create a github workflow to test code file of every PR. created dummy test in tests.py to check github workflow.

also, added a dummy test into meet_balls_app/test_dummy.py file to check github workflow.
will be deleted later by next PR's. 

closes #26

2023-04-16 13:56 UTC, amitKaplansky commented on meet_balls_app/test_dummy.py
When we talked about it in slack yftach mentioned that the dummy test should be in tests.py file because it already exists. 
@yftacherzog Is it ok to leave it like that also?

2023-04-16 14:00 UTC, IdanZimi commented on meet_balls_app/test_dummy.py
At first I put it right there at tests.py, but then the pytest checks didnt work.
after google it. it said pytest is searching for files with the prefix test_ or suffix _test to that's why I changed it.
if there is any other solution preferred I would love to hear

2023-04-16 14:04 UTC, IdanZimi commented on meet_balls_app/test_dummy.py
I updated the PR. created the tests.py file.

2023-04-16 14:16 UTC, amitKaplansky commented on meet_balls_app/test_dummy.py
I think you can add it to the pytest.yml file to configure a certain file or test directories.
I still don't have the answer, working on it.

2023-04-16 14:24 UTC, amitKaplansky commented on meet_balls_app/test_dummy.py
I think you need to add this to the pytest.yml file and it might work. lmk (:
testpaths:
  - meet_balls_app/
python_files:
  - "test_*.py"
  - "tests.py"

2023-04-16 14:24 UTC, IdanZimi commented on meet_balls_app/test_dummy.py
I think the solution (if needed at all) might be pytest.ini file and inside it add the following: 
`[pytest]
python_files = test_*.py *_test.py tests.py
`
is it worth changing? @yftacherzog

2023-04-16 14:27 UTC, IdanZimi commented on meet_balls_app/test_dummy.py
> I think you need to add this to the pytest.yml file and it might work. lmk (: testpaths:
> 
> * meet_balls_app/
>   python_files:
> * "test_*.py"
> * "tests.py"

thanks! let's wait for a reply and move from there

2023-04-16 15:03 UTC, amitCohen2 commented on meet_balls_app/test_dummy.py
> I think the solution (if needed at all) might be pytest.ini file and inside it add the following: `[pytest] python_files = test_*.py *_test.py tests.py ` is it worth changing? @yftacherzog

I think it worth changing

2023-04-16 15:05 UTC, Yuval-Vino commented on meet_balls_app/test_dummy.py
I think you should add `pytest.ini `, as you see without it you can't find files called tests.
this is a problem for us since Django generates for each app test.py if we leave it like this, you should always change the name of the file manually

2023-04-16 15:32 UTC, IdanZimi commented on meet_balls_app/test_dummy.py
How `pytest.ini` related to the github workflow? 
shoudlnt I add some code to the yml file so it can detect files other than _test or test_?
Im confused. @Yuval-Vino

2023-04-16 15:42 UTC, IdanZimi commented on meet_balls_app/test_dummy.py
anyway. I added the `pytest.ini` file. and also added dummy test to tests.py to ensure it check it too. you can see in the checks tab that it work now, it test both files `test_dummy.py` and `tests.py` as well. 
@Yuval-Vino  @amitKaplansky @amitCohen2

2023-04-16 15:46 UTC, Yuval-Vino commented on meet_balls_app/test_dummy.py
@IdanZimi pytest.ini is for customizing some pytest behavior (such as what files to look for)  this should be placed in the root directory of the project
while the yml which is placed in the workflow

2023-04-16 15:48 UTC, Yuval-Vino commented on meet_balls_app/test_dummy.py
@IdanZimi `pytest.ini` is for customizing Pytest behavior (such as which files to look for) and belongs in the project root directory. 
The YAML file used in GitHub workflows defines workflow steps and executes relevant terminal commands (in this case running pytest).

2023-04-16 15:51 UTC, IdanZimi commented on meet_balls_app/test_dummy.py
Got it. So if I didnt tell nothing about which files to look for at the yml file, how github worflows know that it should also test the tests.py file? @Yuval-Vino

2023-04-16 15:55 UTC, Yuval-Vino commented on meet_balls_app/test_dummy.py
basically, the yaml file just runs the `pipenv run pytest -v` command (and some more terminal commands)
the ini file is in charge of this command behavior

2023-04-16 16:04 UTC, Danielsio approved these changes
Isn't there a way to make pytest.ini file just search for every file contains the word test ?
other then that I think you have done a great job.

2023-04-16 16:06 UTC, amitCohen2 commented
Looks like you fixed all the issues. Good job!

2023-04-16 16:17 UTC, IdanZimi commented
> Isnt there a way to make pytest.ini file just search for every file contains the word test ? other then that I think you have done a great job.

There is a way, but not sure if it's necessary. we already have a template to stick to:

-  *_test.py 
-   test_*.py 
-    tests.py

2023-04-16 18:09 UTC, MaayanMashhadi approved these changes

2023-04-16 18:23 UTC, yftacherzog commented on meet_balls_app/test_dummy.py
I don't mind which convention you pick for supported file name formats as long as it allows having multiple test files. The file I provided was just a suggestion. I'm glad you have it figured out!

2023-04-16 18:25 UTC, yftacherzog commented
@IdanZimi I see now that the checks actually did run for this PR, contrary to what I thought is going to happen 😅

2023-04-16 18:28 UTC, yftacherzog commented
@IdanZimi make sure the commit message is following the guidelines on the contributing guide (the title should be `Add PyTest and github workflow` - capitalize, imperative mood, no period)

2023-04-16 18:30 UTC, yftacherzog requested changes
Nice work on both the code and the discussion during code review! Fix the commit message and it can be merged.

2023-04-17 10:27 UTC, yftacherzog approved these changes

2023-04-17 10:27 UTC, merged